apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jira-telegram-bot
  namespace: jira-telegram-bot
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: jira-telegram-bot
  data:
  - secretKey: DB_USERNAME
    remoteRef:
      key: jira-telegram-bot
      property: DB_USERNAME
  - secretKey: DB_PASSWORD
    remoteRef:
      key: jira-telegram-bot
      property: DB_PASSWORD

  - secretKey: TG_TOKEN
    remoteRef:
      key: jira-telegram-bot
      property: TG_TOKEN