apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysite
  namespace: mysite
spec:
  targetNamespace: mysite
  releaseName: mysite
  interval: 1m0s
  chart:
    spec:
      chart: charts/my-own/mysite
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: server