apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysite
  namespace: flux-system
spec:
  targetNamespace: mysite
  releaseName: mysite
  interval: 1m0s
  chart:
    spec:
      chart: charts/my-own/mysite
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: server
  values:
    web:
      protocol: "https"
      host: "jestenok.com"
      port: "8443"

      tls:
        enabled: true

    db:
      name: "site"
      host: "postgres"
      port: "5432"
  valuesFrom:
    - kind: Secret
      name: user
      targetPath: username
      valuesKey: web.superuser.username
    - kind: Secret
      name: user
      targetPath: password
      valuesKey: web.superuser.password

    - kind: Secret
      name: db-user
      targetPath: username
      valuesKey: db.username
    - kind: Secret
      name: db-user
      targetPath: password
      valuesKey: db.password

    - kind: Secret
      name: tls
      targetPath: tls.crt
      valuesKey: web.tls.cert
    - kind: Secret
      name: tls
      targetPath: tls.key
      valuesKey: web.tls.key
