apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mysite
  namespace: flux-system
spec:
  targetNamespace: mysite
  releaseName: mysite
  interval: 1m0s
  chart:
    spec:
      chart: charts/my-own/mysite
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: server
  values:
    web:
      protocol: "https"
      host: "jestenok.com"
      port: "8443"

      tls:
        enabled: true
        cert: ""
        key: ""

    db:
      name: "site"
      host: "postgres"
      port: "5432"
