apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: filebeat
  namespace: eck
spec:
  type: filebeat
  image: "elastic/filebeat:8.6.2"
  version: 8.6.2
  elasticsearchRef:
    name: elastic
  kibanaRef:
    name: kibana
  config:
    filebeat.inputs:
    - type: container
      scan_frequency: 10s
      paths:
      - /var/log/containers/jira*.log
      multiline.pattern: '^[[:space:]]'
      multiline.negate: false
      multiline.match: after
      processors:
#      - add_kubernetes_metadata:
#          host: ${NODE_NAME}
#          matchers:
#          - logs_path:
#              logs_path: "/var/log/containers/"
      - dissect:
          tokenizer: "%{date} %{time} [%{thread}] [%{log_level}] method: %{method}, url: %{url}, json: %{json}"
          field: "message"
          target_prefix: "dissect"
      - decode_json_fields:
          fields: ["dissect.json"]
          target: "json"
          process_array: true
          max_depth: 3
          overwrite_keys: true
          add_error_key: true
    setup:
      dashboards:
        enabled: true
  daemonSet:
    podTemplate:
      spec:
        serviceAccountName: filebeat
        automountServiceAccountToken: true
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirstWithHostNet
        hostNetwork: true # Allows to provide richer host metadata
        priorityClassName: system-node-critical
        containers:
        - name: filebeat
          resources:
            limits:
              memory: 1Gi
              cpu: 1
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: varlogcontainers
            mountPath: /var/log/containers
          - name: varlogpods
            mountPath: /var/log/pods
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
        volumes:
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers