kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: jira-telegram-bot
  name: jira-telegram-bot
  namespace: jira-telegram-bot
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    k8s-app: jira-telegram-bot