apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: mysite
  namespace: flux-system
spec:
  secretRef:
    name: dockerhub
  image: registry.hub.docker.com/jestenok/mysite
  interval: 1m0s