apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: flux-system
spec:
  targetNamespace: elk
  releaseName: kibana
  interval: 1m0s
  chart:
    spec:
      chart: charts/elk/kibana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: server
  values:
    image: "kibana"
    imageTag: "8.6.2"
    ingress:
      enabled: false
      className: "nginx"
      pathtype: ImplementationSpecific
      annotations:
        nginx.ingress.kubernetes.io/ssl-certificate: wildcard-tls
      hosts:
        - host: kibana.jestenok.com
          paths:
            - path: /
      tls:
        - hosts:
            - kibana.jestenok.com
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"