apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: flux-system
spec:
  targetNamespace: elk
  releaseName: kibana
  interval: 1m0s
  chart:
    spec:
      chart: charts/elk/kibana
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: server
  values:
    ingress:
      enabled: true
      hosts:
        - host: kibana.jestenok.com