apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mysite
  namespace: flux-system
spec:
  secretRef:
    name: bearer-token-auth
  interval: 1m
  url: https://github.com/jestenok/mysite
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/