apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira
  namespace: jira
spec:
  capacity:
    storage: 8Gi
  hostPath:
    path: /code/storage/jira
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: jira
    name: jira
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira
  namespace: jira
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: jira
  storageClassName: local-path
  volumeMode: Filesystem