apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: jira-telegram-bot
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jira-telegram-bot
  policy:
    semver:
      range: '>=1.0.0'