apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
spec:
  targetNamespace: jenkins
  releaseName: jenkins
  interval: 1m0s
  chart:
    spec:
      chart: charts/foreign/jenkins
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: server
  valuesFrom:
    - kind: Secret
      name: user
      valuesKey: username
      targetPath: controller.adminUser
    - kind: Secret
      name: user
      valuesKey: password
      targetPath: controller.adminPassword
  values:
    controller:
      numExecutors: 0
      ingress:
        enabled: true
        hostName: jenkins.jestenok.com
        ingressClassName: nginx
    agent:
      image: benhall/dind-jenkins-agent:v2
      additionalContainers:
        - sideContainerName: dind
          image: docker
          tag: dind
          command: dockerd-entrypoint.sh
          args: ""
          privileged: true
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
