apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
spec:
  targetNamespace: jenkins
  releaseName: jenkins
  interval: 1m0s
  chart:
    spec:
      chart: charts/foreign/jenkins
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: server
  valuesFrom:
    - kind: Secret
      name: user
      valuesKey: username
      targetPath: controller.adminUser
    - kind: Secret
      name: user
      valuesKey: password
      targetPath: controller.adminPassword
  values:
    controller:
      numExecutors: 0
      ingress:
        enabled: true
        hostName: jenkins.jestenok.com
        ingressClassName: nginx
      installPlugins:
        - kubernetes:3734.v562b_b_a_627ea_c
        - workflow-aggregator:590.v6a_d052e5a_a_b_5
        - git:4.13.0
        - configuration-as-code:1569.vb_72405b_80249
        - blueocean:1.27.0
        - docker-workflow:1.26
    additionalAgents:
      python:
        podName: python
        customJenkinsLabels: python
        sideContainerName: python
        image: python
        tag: "3"
        command: "/bin/sh -c"
        args: "cat"
        TTYEnabled: true
      docker:
        podName: docker
        image: benhall/dind-jenkins-agent:v2
        tag: latest
        resources:
          requests:
            cpu: 100m
            memory: 2048Mi
          limits:
            cpu: 100m
            memory: 2048Mi