apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
spec:
  targetNamespace: jenkins
  releaseName: jenkins
  interval: 1m0s
  chart:
    spec:
      chart: charts/foreign/jenkins
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: server
  valuesFrom:
    - kind: Secret
      name: user
      valuesKey: username
      targetPath: controller.adminUser
    - kind: Secret
      name: user
      valuesKey: password
      targetPath: controller.adminPassword
  values:
    controller:
      ingress:
        enabled: true
        hostName: jenkins.jestenok.com
        ingressClassName: nginx
      JCasC:
        configScripts:
          this-is-where-i-configure-the-executors: |
            jenkins:
              numExecutors: 0
      installPlugins:
        - kubernetes
        - blueocean
        - docker-workflow
        - workflow-aggregator
        - workflow-job
        - credentials-binding
        - git
        - configuration-as-code
    podTemplates:
      python: |
        - name: python
          label: jenkins-python
          serviceAccount: jenkins
          containers:
            - name: python
              image: python:3
              command: "/bin/sh -c"
              args: "cat"
              ttyEnabled: true
              privileged: true
              resourceRequestCpu: "400m"
              resourceRequestMemory: "512Mi"
              resourceLimitCpu: "1"
              resourceLimitMemory: "1024Mi"
      docker: |
        - name: docker
          label: jenkins-docker
          serviceAccount: jenkins
          containers:
            - name: docker
              image: benhall/dind-jenkins-agent:v2
              ttyEnabled: true
              privileged: true
              resourceRequestCpu: "100m"
              resourceRequestMemory: "2048Mi"
              resourceLimitCpu: "100m"
              resourceLimitMemory: "2048Mi"

    agent:
      podName: default
      customJenkinsLabels: default
      resources:
        limits:
          cpu: "1"
          memory: "2048Mi"
    additionalAgents:
      python:
        podName: python
        customJenkinsLabels: python
        sideContainerName: python
        image: python
        tag: "3"
        command: "/bin/sh -c"
        args: "cat"
        TTYEnabled: true
      docker:
        podName: docker
        image: benhall/dind-jenkins-agent:v2
        tag: latest
        resources:
          requests:
            cpu: 100m
            memory: 2048Mi
          limits:
            cpu: 100m
            memory: 2048Mi