apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: flux-system
spec:
  targetNamespace: jenkins
  releaseName: jenkins
  interval: 1m0s
  chart:
    spec:
      chart: charts/foreign/jenkins
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: server
  valuesFrom:
    - kind: Secret
      name: user
      valuesKey: username
      targetPath: controller.adminUser
    - kind: Secret
      name: user
      valuesKey: password
      targetPath: controller.adminPassword
  values:
    controller:
      ingress:
        enabled: true
        hostName: jenkins.jestenok.com
        ingressClassName: nginx
      installPlugins:
        - kubernetes
        - blueocean
        - docker-workflow
        - workflow-aggregator
        - workflow-job
        - credentials-binding
        - git
        - configuration-as-code
        - docker-plugin
        - docker-build-step
    agent:
      disableDefaultAgent: true
    additionalAgents:
      python:
        podName: docker
        customJenkinsLabels: docker
        sideContainerName: docker
        image: docker
        tag: "latest"
        TTYEnabled: true

