apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tls
  namespace: flux-system
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: tls
  data:
  - secretKey: tls.crt
    remoteRef:
      key: tls
      property: cert
  - secretKey: tls.key
    remoteRef:
      key: tls
      property: key