{
 "title": "monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "cpu temp (min)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  cpu_temp\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "cpu temp (avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  cpu_temp\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "cpu temp (max)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  cpu_temp\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  cpu_usage\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "cpu temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  cpu_temp\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "time of proc",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  time_of_proc\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "free mem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  mem_available /1024 /1024\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  }
 ]
}