version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '8443:8443'
    volumes:
      - /code/mysite/volumes/static:/code/static
      - /code/mysite/volumes/media:/code/media
      - /code/nginx/ssl:/etc/ssl
      - /code/nginx/jestenok.com.conf:/etc/nginx/conf.d/jestenok.com.conf
    env_file:
      - .env