apiVersion: v1
kind: Secret
metadata:
  name: main-tls
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.web.tls.cert }}
  tls.key: {{ .Values.web.tls.key }}