apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: server
  namespace: flux-system
spec:
  secretRef:
    name: flux-system
  interval: 1m
  url: ssh://git@github.com/jestenok/server
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/