kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: nginx
  name: nginx
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: nginx
  template:
    metadata:
      labels:
        k8s-app: nginx
    spec:
      volumes:
        - name: nginx
          hostPath:
            path: /code/volumes/mysite
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: nginx