kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: nginx
  name: nginx
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    k8s-app: nginx