{
 "title": "monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "cpu temp (min)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  cpu_temp\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "cpu temp (avg)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  cpu_temp\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "cpu temp (max)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  cpu_temp\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "telegram",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  telegram_status\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "jira",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  jira_status\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "site",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  site_status\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "airflow",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  airflow_status\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "adminer",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  adminer_status\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "cpu temp",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  cpu_temp\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "free RAM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  mem_available /1024 /1024 as mb\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  cpu_usage\nFROM monitoring.metrics\nWHERE\n  $__timeFilter(timestamp)\nORDER BY 1"
    }
   ]
  }
 ]
}