apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: eck
spec:
  image: "kibana:8.6.2"
  version: 8.6.2
  count: 1
  elasticsearchRef:
    name: elastic
  http:
    service:
      spec:
        type: ClusterIP
        ports:
          - name: http
            port: 5601
            targetPort: 5601
            protocol: TCP
    tls:
      certificate:
        secretName: wildcard-tls