apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: django
  namespace: mysite
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: django
  data:
  - secretKey: secret-key
    remoteRef:
      key: django
      property: secret-key