apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-example
  namespace: mysite
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: main-tls
    type: kubernetes.io/tls
  data:
  - secretKey: tls.crt
    remoteRef:
      key: tls
      property: cert
  - secretKey: tls.key
    remoteRef:
      key: tls
      property: key