apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: jira
spec:
  {{ if .Values.web.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.web.host }}
      secretName: tls
  {{- end}}
  ingressClassName: nginx
  rules:
  - host: {{ .Values.web.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: jira
              port:
                number: 8080