apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: logstash
  namespace: flux-system
spec:
  targetNamespace: elk
  releaseName: logstash
  interval: 1m0s
  chart:
    spec:
      chart: charts/elk/logstash
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: server
  values:
    image: "logstash"
    imageTag: "8.6.2"
#    logstashPipeline:
#      logstash.conf: |
#        input {
#          beats {
#            port => 5044
#          }
#        }
#        output { elasticsearch { hosts => http://elasticsearch-master:9200 } }