apiVersion: v1
kind: Secret
metadata:
  name: db-user
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/basic-auth
data:
  username: {{.Values.db.username | b64enc}}
  password: {{.Values.db.password | b64enc}}