kind: ConfigMap
apiVersion: v1
metadata:
  name: mysite
data:
  domainname: {{.Values.web.host | quote}}
  db_name: {{.Values.db.name | quote}}
  db_host: {{.Values.db.host | quote}}
  db_port: {{.Values.db.port | quote}}