apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: mysite
spec:
  ingressClassName: nginx
  {{ if .Values.web.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.web.host }}
      secretName: main-tls
  {{- end}}
  rules:
  - host: {{ .Values.web.host }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: mysite
              port:
                number: 8000
        - path: /static
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 80
        - path: /media
          pathType: Prefix
          backend:
            service:
              name: nginx
              port:
                number: 80