apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: kube-prometheus-stack
spec:
  interval: 1m
  url: https://prometheus-community.github.io/helm-charts
# Path: cluster/kube-prometheus-stack/kustomization.yaml