apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: kube-prometheus-stack
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-community/kube-prometheus-stack
      sourceRef:
        kind: <HelmRepository|GitRepository|Bucket>
        name: prometheus-community
        namespace: kube-prometheus-stack
      interval: 1m