apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: jira-telegram-bot
  namespace: flux-system
spec:
  secretRef:
    name: github
  interval: 5m
  url: ssh://git@github.com/jestenok/jira-telegram-bot
  ref:
    branch: master