kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: jira
  name: jira
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    k8s-app: jira