kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: jira
  name: jira
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - port: {{ .Values.web.port | quote }}
      targetPort: {{ .Values.web.port | quote }}
  selector:
    k8s-app: jira