apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: flux-system
spec:
  targetNamespace: vault
  releaseName: vault
  interval: 15m0s
  chart:
    spec:
      chart: charts/secrets/vault
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: server
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: vault.jestenok.com
      ha:
        enabled: true
        replicas: 1
    ui:
      enabled: true