apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-access
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-access
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-access
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: secret-access
subjects:
- kind: ServiceAccount
  name: secret-access
  namespace: flux-system