apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-telegram-bot
  namespace: jira-telegram-bot
spec:
  capacity:
    storage: 8Gi
  hostPath:
    path: /code/storage/jira-telegram-bot
    type: DirectoryOrCreate
  accessModes:
    - ReadWriteOnce
  claimRef:
    kind: PersistentVolumeClaim
    namespace: jira-telegram-bot
    name: jira-telegram-bot
  storageClassName: local-path
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-telegram-bot
  namespace: jira-telegram-bot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: jira-telegram-bot
  storageClassName: local-path
  volumeMode: Filesystem