kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: jira-telegram-bot
  name: jira-telegram-bot
  namespace: jira-telegram-bot
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: jira-telegram-bot
  template:
    metadata:
      labels:
        k8s-app: jira-telegram-bot
    spec:
      containers:
        - name: jira-telegram-bot
          image: registry.hub.docker.com/jestenok/jira-telegram-bot:1.0.4 # {"$imagepolicy": "flux-system:jira-telegram-bot"}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: jira-telegram-bot
                  key: db_name
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: jira-telegram-bot
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: jira-telegram-bot
                  key: db_port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user
                  key: password
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: telegram
                  key: token
            - name: JIRA_HOST
              valueFrom:
                configMapKeyRef:
                  name: jira-telegram-bot
                  key: jira_host
            - name: JIRA_PUBLIC_DOMAINNAME
              valueFrom:
                configMapKeyRef:
                  name: jira-telegram-bot
                  key: jira_public_domainname
