kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: postgres
  name: postgres
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: postgres
  template:
    metadata:
      labels:
        k8s-app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.db.port }}
              name: http
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: db_name
                  name: site
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: db_username
                  name: site
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: db_password
                  name: site