apiVersion: v1
kind: Secret
metadata:
  name: db-user
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/basic-auth
data:
  username: {{.Values.db.username  | quote}}
  password: {{.Values.db.password  | quote}}