kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: postgres
  name: postgres
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - port: {{.Values.db.port}}
      targetPort: {{.Values.db.port}}
  selector:
    k8s-app: postgres