kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: postgres
  name: postgres
  namespace: jira-telegram-bot
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    k8s-app: postgres