apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Receiver
metadata:
  name: server
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: github
  resources:
    - kind: GitRepository
      name: server