apiVersion: v1
kind: Secret
metadata:
  name: main-tls
  namespace: kubernetes-dashboard
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.cert | b64enc }}
  tls.key: {{ .Values.key | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: main-tls
  namespace: kube-system
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.cert | b64enc }}
  tls.key: {{ .Values.key | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: main-tls
  namespace: argocd
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.cert | b64enc }}
  tls.key: {{ .Values.key | b64enc }}

---
