apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  interval: 5m
  targetNamespace: kube-system
  values:
    controller:
      service:
        ports:
          http: 80
          https: 8443
#TODO: Добавить TLS через вольт или хз еще что
#      extraArgs:
#        default-ssl-certificate: "kube-system/main-tls"