apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
#  https://kubernetes.github.io/ingress-nginxs/index.yaml
#  https://kubernetes.github.io/ingress-nginx/index.html