apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jestenok/server.git'
    path: k8s/mysite
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: 'password'
          value: $(PASSWORD)
        - name: 'web.tls.cert'
          value: $(CRT)
        - name: 'web.tls.key'
          value: $(KEY)
        - name: 'djangoSecretKey'
          value: $(DJANGO)
      releaseName: mysite
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: mysite

