{{- if eq .Values.general.useVault true }}

apiVersion: v1
kind: Secret
metadata:
  name: user
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.general.username | b64enc }}
  password: {{ .Values.general.password | b64enc  }}

{{- else }}

apiVersion: v1
kind: Secret
metadata:
  name: user
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.general.username | b64enc }}
  password: {{ .Values.general.password | b64enc  }}

{{- end}}