apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: jira-telegram-bot
  name: jira-telegram-bot
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jestenok.com
  rules:
  - host: jestenok.com
    http:
      paths:
        - path: /jira-telegram-bot/
