apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dockerhub
  namespace: flux-system
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: dockerhub
    type: kubernetes.io/overconfidence
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: dockerhub
      property: config