apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github
  namespace: flux-system
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: github
  data:
  - secretKey: token
    remoteRef:
      key: github
      property: token
  - secretKey: git.asc
    remoteRef:
      key: github
      property: git.asc
  - secretKey: username
    remoteRef:
      key: user
      property: username
  - secretKey: password
    remoteRef:
      key: user
      property: password
