apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github
  namespace: flux-system
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: github
  data:
  - secretKey: token
    remoteRef:
      key: token
      property: token