apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github
  namespace: flux-system
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: github
    template:
      type: Opaque
      metadata:
        name: bearer-token-auth
  data:
  - secretKey: bearerToken
    remoteRef:
      key: github
      property: token